#!/usr/bin/env python3
"""
Clean all generated output files.

This script removes all files generated by the pipeline, including:
- output/ directory (legacy mode)
- experiments/runs/ (versioned mode) - keeps directory structure

Usage:
    python clean_outputs.py
    uv run python clean_outputs.py
"""

import shutil
from pathlib import Path


def clean_outputs():
    """Remove all generated output files."""
    project_root = Path(__file__).parent
    
    print("🧹 Cleaning generated outputs...")
    print()
    
    # Clean output/ directory (legacy)
    output_dir = project_root / "output"
    if output_dir.exists():
        print(f"📁 Removing {output_dir}")
        shutil.rmtree(output_dir)
        print(f"   ✓ Deleted")
    else:
        print(f"📁 {output_dir} - Not found (skipping)")
    
    print()
    
    # Clean experiments/runs/ (versioned mode)
    runs_dir = project_root / "experiments" / "runs"
    if runs_dir.exists():
        experiment_dirs = [d for d in runs_dir.iterdir() if d.is_dir() and d.name.startswith("exp_")]
        if experiment_dirs:
            print(f"📁 Found {len(experiment_dirs)} experiment(s) in {runs_dir}")
            for exp_dir in experiment_dirs:
                print(f"   Removing {exp_dir.name}")
                shutil.rmtree(exp_dir)
            print(f"   ✓ Deleted {len(experiment_dirs)} experiment(s)")
        else:
            print(f"📁 {runs_dir} - No experiments found")
    else:
        print(f"📁 {runs_dir} - Not found (skipping)")
    
    print()
    print("✅ Cleanup complete!")


if __name__ == "__main__":
    import sys
    
    # Ask for confirmation
    response = input("❗ This will delete all generated outputs. Continue? (y/N): ")
    if response.lower() not in ["y", "yes"]:
        print("❌ Cancelled")
        sys.exit(0)
    
    clean_outputs()
